## Igår: 
setup - repo, folderstruktur, installationer (numpy, pandas, seaborn, matplotlib, openpyxl, ipykernel) 
- Pandas och Seaborn
- Series object
- DataFrame object
- Index object
- Selections, filtering, masking, rename, sorting ...
- Summativa beskrivningar av data -> info(), describe(), unique(), head(), tail()
- Visualiserar mha Seaborn

---
# Lecture notes - Pandas - missing data & aggregations

---
This is the lecture note for **Pandas missing data & aggregations** - but it's built upon contents from previous course: 
- Python programming

Read more 

- [documentation - read_csv](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html)

- [documentation - aggregate](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.aggregate.html)

- [documentation - groupby](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.groupby.html)

- [documentation - missing values](https://pandas.pydata.org/pandas-docs/stable/user_guide/missing_data.html)
---

## Setup
- create dummy DataFrame
- it's very useful to create dummy DataFrame in order to test and learn Pandas methods

In [16]:
import numpy as np 
import pandas as pd
#np.random.seed(42)

n = 8
random_matrix = np.random.randint(1,10, (n,n))
#It returns an array of specified shape and fills it with random integers from low (inclusive) to high (exclusive), i.e. in the interval [low, high).
print(random_matrix)
index = np.random.choice(random_matrix.size, 10, replace = False)
#random.choice(a, size=None, replace=True, p=None). Generates a random sample from a given 1-D array: a
print(f"index {index}")
print(f"Flattens the matrix: {random_matrix.ravel()}")

random_matrix = random_matrix*1.0 # to convert it to float as np.nan is float
random_matrix.ravel()[index] = None # returns contiguous flattened array
# numeric containers always use NaN 
print(random_matrix)

[[3 6 1 7 1 9 1 1]
 [7 2 5 8 8 3 7 3]
 [6 6 3 7 3 8 4 1]
 [4 7 4 6 9 1 5 7]
 [1 4 6 2 5 1 6 6]
 [4 8 4 8 8 5 4 2]
 [3 3 4 4 5 4 8 6]
 [6 8 7 8 2 9 1 8]]
index [16 50 17 23 56 57 31 53 60 45]
Flattens the matrix: [3 6 1 7 1 9 1 1 7 2 5 8 8 3 7 3 6 6 3 7 3 8 4 1 4 7 4 6 9 1 5 7 1 4 6 2 5
 1 6 6 4 8 4 8 8 5 4 2 3 3 4 4 5 4 8 6 6 8 7 8 2 9 1 8]
[[ 3.  6.  1.  7.  1.  9.  1.  1.]
 [ 7.  2.  5.  8.  8.  3.  7.  3.]
 [nan nan  3.  7.  3.  8.  4. nan]
 [ 4.  7.  4.  6.  9.  1.  5. nan]
 [ 1.  4.  6.  2.  5.  1.  6.  6.]
 [ 4.  8.  4.  8.  8. nan  4.  2.]
 [ 3.  3. nan  4.  5. nan  8.  6.]
 [nan nan  7.  8. nan  9.  1.  8.]]
